services:
  app1:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app1
    expose:
      - 3000
    environment:
      - APPNAME=app1
    ports:
      - 3001:3000

  app2:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app2
    expose:
      - 3000
    environment:
      - APPNAME=app2
    ports:
      - 3002:3000

  loadbalancer:
    build: ./nginx
    container_name: loadbalancer
    expose:
      - 80
    ports:
      - 8080:80
    depends_on:
      - app1
      - app2

networks:
  default:
